# Generated by Django 4.1 on 2024-04-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=1200)),
                ('seller_name', models.CharField(max_length=120)),
                ('seller_address', models.TextField()),
                ('seller_contact', models.PositiveIntegerField()),
                ('seller_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(max_length=1200, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=500)),
                ('product_price', models.FloatField()),
                ('product_image', models.ImageField(upload_to='product')),
                ('product_seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.seller')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
        ),
    ]
