# Generated by Django 4.1 on 2024-05-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_purchase_freq',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
