# Generated by Django 5.0.7 on 2024-11-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rating_user_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.TextField(blank=True),
        ),
    ]
